<?php declare(strict_types=1);


namespace EdmondsCommerce\SamTrainingXML\Tests;

use EdmondsCommerce\SamTrainingXML\Reddit\SimpleXML;
use PHPUnit\Framework\TestCase;

class SimpleXMLTest extends TestCase
{

    /**
     * @var SimpleXML
     */
    private $simpleXML;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->simpleXML = new SimpleXML();
    }

    /**
     * @test
     *
     */
    public function itReturnsAnXMLString(): void
    {

        $expected = '<?xml version="1.0" encoding="UTF-8"?>
<root/>
';
        $actual = $this->simpleXML->getXML();
        self::assertSame($expected, $actual);
    }

}
