<?php declare(strict_types=1);


namespace EdmondsCommerce\SamTrainingXML\Tests\Reddit;

use EdmondsCommerce\SamTrainingXML\Reddit\SimpleXML;
use PHPUnit\Framework\TestCase;

class SimpleXMLTest extends TestCase
{

    /**
     * @var SimpleXML
     */
    private $simpleXML;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->simpleXML = new SimpleXML();
    }

    /**
     * @test
     *
     */
    public function itReturnsAnXMLString(): void
    {

        $expected = '';
        $actual = $this->simpleXML->getXML();
        self::assertSame($expected, $actual);
    }

}
